### PR TITLE
fix: add local build scripts

### PR DESCRIPTION
**Pull request by ArwynFr**
Adds a script to make a local version of the mod for testing purposes

### CODE REVIEW

**Comment by ArwynFr** [comment]
@PhileasLX if you want to test it, you need to:

- [Install PWSH 7](https://github.com/PowerShell/powershell/releases)
- Set an environment variable named `ARMA3TOOLS` pointing to your arma tools directory
- Run `.local\Make.ps1` script
- The mod goes into `out` directory

**Review by ImplicitDeny — APPROVED** [review]
Works as expected, as long as one does not expect it to sign PBOs, which is acceptable on a local test build

**Comment by ArwynFr** [comment]
Yes, I did not include pbo signing as I didn't thought that feature would be very useful there.

**Comment by PhileasLX** [comment]
Works as expected.

**Pull request merged**
